// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:tunely/features/lyrics/model/lyrics_line.dart';
import 'package:tunely/features/lyrics/model/lyrics_result.dart';
import 'package:tunely/features/music_management/model/management_settings.dart';
import 'package:tunely/features/stats/model/tune_stats.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LyricsLineAdapter());
    registerAdapter(LyricsResultAdapter());
    registerAdapter(ManagementSettingsAdapter());
    registerAdapter(TuneStatsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LyricsLineAdapter());
    registerAdapter(LyricsResultAdapter());
    registerAdapter(ManagementSettingsAdapter());
    registerAdapter(TuneStatsAdapter());
  }
}
